### ISSUE TITLE
Change status on agent reply

### ISSUE THREAD

**Issue by nandi96** [stefanclark/osticket-statuschange#1]
Hi,
How can I modify the source code to do this:
If the ticket status is: "Status01" and an agent answer, immediately change to "Status02".

**Comment by stefanclark** [comment]
I would probably do the following:

- add a config to select if the status change is triggered by agent and/or user
- add listener to agent reply
- check new config setting before changing status

**Comment by nandi96** [comment]
Can you help me with the implementation?
