### ISSUE TITLE
unexpected behavior

### ISSUE THREAD

**Issue by nandi96** [stefanclark/osticket-statuschange#2]
When we answer a ticket, the plugin change the status incorrectly.

Debug log:
Plugin: StatusChange
statusChange: Current status does not match (22 != 1)

**Comment by stefanclark** [comment]
I would need more information to understand why it is not working as expected.
1. What rule(s) (instances) have you set up?
2. What is the status of the ticket before you answer?
3. What status has the agent selected with answering the ticket?
4. What status is the ticket after the agent answers.

The log message suggests the ticket has been set to status with id = 22 and the rule created is to change from status with id = 1

**Comment by nandi96** [comment]
> I would need more information to understand why it is not working as expected.
> 
> 1. What rule(s) (instances) have you set up?
> 2. What is the status of the ticket before you answer?
> 3. What status has the agent selected with answering the ticket?
> 4. What status is the ticket after the agent answers.
> 
> The log message suggests the ticket has been set to status with id = 22 and the rule created is to change from status with id = 1

1. Instance: Staff answer
Current status: ID 24
New status: ID 25

2. The ticket status is ID 24, before the staff answer.
3. The staff can not change the status manually, this field is hidden on the staff panel.
4. The status is ID 20, after the staff answer. 

We tested again the process, see below the error messages:
statusChange: Current status does not match (24 != 21)
statusChange: Current status does not match (24 != 20)
statusChange: Current status does not match (24 != 1)
statusChange: Updating status (24 => 25)
statusChange: Updating status (25 => 20)

We use this active instances:
1. Agent answer
Current status: ID 1
New status: ID 22

2. Agent aswer
Current status: ID 24
New status: ID 25

3. Agent answer
Current status: ID 25
New status: ID 20

4. Agent answer
Current status: ID 20
New status: ID 21

5. Agent answer
Current status: ID 21
New status: ID 22

**Comment by stefanclark** [comment]
What version of osTicket are you running?

**Comment by nandi96** [comment]
> What version of osTicket are you running?

Tested with: osTicket v1.18 (https://github.com/osTicket/osTicket/commit/724de4563e736cdde7c2e2dabe839b232eb5438f)
Apache/2.4.57 (Unix)
MariaDB 10.3.37
PHP 8.2.5

**Comment by stefanclark** [comment]
You can see from the debug that all instances will be evaluated, and each instance doesn't care if a previous instance already changed the status. I don't know if osTicket calls the instances in any predictable order.

I hadn't considered your use case where multiple rules might form a chain.

**Comment by nandi96** [comment]
Yes, I know, but we used it for a month so that only one instance ran after the given answer. and nothing changed.

**Comment by stefanclark** [comment]
Try out the latest version 0.3

**Comment by nandi96** [comment]
Tested, working normally. Thanks for quick help!
